version: '3.8'

services:
  firecrawl-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: firecrawl-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEFAULT_API_ENDPOINT=${NEXT_PUBLIC_DEFAULT_API_ENDPOINT:-https://firecrawl.bitop.dev}
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - firecrawl-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: firecrawl-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - firecrawl-frontend
    networks:
      - firecrawl-network
    restart: unless-stopped
    profiles:
      - nginx

networks:
  firecrawl-network:
    driver: bridge
    name: firecrawl-network

volumes:
  nginx_cache:
