version: '3.8'

services:
  firecrawl-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: firecrawl-frontend-dev
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DEFAULT_API_ENDPOINT=https://firecrawl.bitop.dev
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped
    networks:
      - firecrawl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  firecrawl-network:
    driver: bridge
    name: firecrawl-network

volumes:
  node_modules:
  next_cache:
